/********************************************************************************
** Form generated from reading UI file 'reservationwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.7
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_RESERVATIONWINDOW_H
#define UI_RESERVATIONWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCalendarWidget>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ReservationWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *RoomReservation;
    QLabel *parkingNeededLabel;
    QPushButton *calendarPushButton;
    QDateEdit *dateEdit;
    QLabel *numberOfGuestsLabel;
    QRadioButton *yesButton;
    QRadioButton *noButton;
    QLabel *guestNameLabel;
    QLabel *datesStayingLabel;
    QLabel *guestNameDescription;
    QLabel *datesDescription;
    QSpinBox *adultGuestsSpinBox;
    QSpinBox *childrenGuestsSpinBox;
    QLabel *adultsAndChildrenLabel;
    QPushButton *nextPageButton;
    QComboBox *roomTypeComboBox;
    QSpinBox *numNightsSpinBox;
    QLabel *startingDateLabel;
    QLabel *numNightsLabel;
    QCalendarWidget *calendarWidget;
    QLabel *errorLabel;
    QLabel *estimatedCostLabel;
    QLabel *estimatedCostTargetLabel;
    QWidget *Payment;
    QPlainTextEdit *nameOnCardTextEdit;
    QLabel *nameOnCardLabel;
    QLabel *cardNumberLabel;
    QComboBox *cardTypeComboBox;
    QLabel *cardTypeLabel;
    QPushButton *nextPageButton_2;
    QPushButton *prevPageButton_2;
    QLineEdit *cardNumberInputBox;
    QSpinBox *expirationMonthSpinBox;
    QSpinBox *expirationYearSpinBox;
    QLabel *expirationMonthLabel;
    QLabel *expirationYearLabel;
    QLabel *expirationLabel;
    QLabel *chargesLabel;
    QLabel *roomCostLabel;
    QLabel *parkingCostLabel;
    QLabel *resortFeesCostLabel;
    QLabel *taxCostLabel;
    QLabel *totalCostLabel;
    QLabel *totalCostDollarsLabel;
    QLabel *parkingCostDollarsLabel;
    QLabel *roomDollarsLabel;
    QLabel *taxDollarsLabel;
    QLabel *resortFeesDollarsLabel;
    QLabel *paymentInformationLabel;
    QPushButton *payButton;
    QWidget *ConfirmationPage;
    QLabel *reservationDetailsLabel;
    QLabel *firstDayLabel;
    QLabel *howManyNightsLabel;
    QLabel *roomTypeLabel;
    QLabel *parkingLabel;
    QLabel *adultsLabel;
    QLabel *childrenLabel;
    QLabel *paymentInformationLabel_2;
    QLabel *totalAmountLabel;
    QLabel *paidWithCardLabel;
    QPushButton *closeButton;
    QLabel *closingLabel;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *ReservationWindow)
    {
        if (ReservationWindow->objectName().isEmpty())
            ReservationWindow->setObjectName(QStringLiteral("ReservationWindow"));
        ReservationWindow->resize(367, 506);
        centralwidget = new QWidget(ReservationWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 371, 461));
        QPalette palette;
        QBrush brush(QColor(223, 223, 223, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(3, 79, 132, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(239, 239, 239, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        QBrush brush3(QColor(239, 239, 239, 128));
        brush3.setStyle(Qt::SolidPattern);
        //palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        //palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush3);
        QBrush brush4(QColor(190, 190, 190, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        QBrush brush5(QColor(0, 0, 0, 128));
        brush5.setStyle(Qt::SolidPattern);
        //palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush5);
        stackedWidget->setPalette(palette);
        QFont font;
        font.setFamily(QStringLiteral("Roboto"));
        font.setPointSize(12);
        stackedWidget->setFont(font);
        stackedWidget->setStyleSheet(QStringLiteral("background-color: rgb(3, 79, 132);"));
        RoomReservation = new QWidget();
        RoomReservation->setObjectName(QStringLiteral("RoomReservation"));
        parkingNeededLabel = new QLabel(RoomReservation);
        parkingNeededLabel->setObjectName(QStringLiteral("parkingNeededLabel"));
        parkingNeededLabel->setGeometry(QRect(30, 330, 231, 21));
        QPalette palette1;
        QBrush brush6(QColor(238, 238, 238, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        parkingNeededLabel->setPalette(palette1);
        parkingNeededLabel->setFont(font);
        calendarPushButton = new QPushButton(RoomReservation);
        calendarPushButton->setObjectName(QStringLiteral("calendarPushButton"));
        calendarPushButton->setGeometry(QRect(90, 170, 31, 31));
        dateEdit = new QDateEdit(RoomReservation);
        dateEdit->setObjectName(QStringLiteral("dateEdit"));
        dateEdit->setGeometry(QRect(30, 170, 91, 31));
        QPalette palette2;
        QBrush brush7(QColor(0, 0, 0, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush7);
        QBrush brush8(QColor(3, 103, 170, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush8);
        QBrush brush9(QColor(4, 155, 255, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush9);
        QBrush brush10(QColor(3, 129, 212, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush10);
        QBrush brush11(QColor(1, 51, 85, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush11);
        QBrush brush12(QColor(2, 68, 113, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush12);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush7);
        QBrush brush13(QColor(255, 255, 255, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush13);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush7);
        QBrush brush14(QColor(129, 179, 212, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        QBrush brush15(QColor(255, 255, 220, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush15);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush7);
        //palette2.setBrush(QPalette::Active, QPalette::PlaceholderText, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush11);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush12);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush13);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush15);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush7);
        //palette2.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush11);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush11);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush11);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush13);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush11);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush15);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush7);
        //palette2.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush5);
        dateEdit->setPalette(palette2);
        QFont font1;
        font1.setFamily(QStringLiteral("Roboto"));
        font1.setPointSize(10);
        dateEdit->setFont(font1);
        numberOfGuestsLabel = new QLabel(RoomReservation);
        numberOfGuestsLabel->setObjectName(QStringLiteral("numberOfGuestsLabel"));
        numberOfGuestsLabel->setGeometry(QRect(30, 210, 141, 41));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        numberOfGuestsLabel->setPalette(palette3);
        numberOfGuestsLabel->setFont(font);
        yesButton = new QRadioButton(RoomReservation);
        yesButton->setObjectName(QStringLiteral("yesButton"));
        yesButton->setGeometry(QRect(130, 360, 99, 20));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        yesButton->setPalette(palette4);
        QFont font2;
        font2.setFamily(QStringLiteral("Roboto Condensed"));
        font2.setPointSize(12);
        yesButton->setFont(font2);
        noButton = new QRadioButton(RoomReservation);
        noButton->setObjectName(QStringLiteral("noButton"));
        noButton->setGeometry(QRect(200, 360, 99, 20));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        noButton->setPalette(palette5);
        noButton->setFont(font2);
        noButton->setChecked(true);
        guestNameLabel = new QLabel(RoomReservation);
        guestNameLabel->setObjectName(QStringLiteral("guestNameLabel"));
        guestNameLabel->setGeometry(QRect(30, 0, 131, 21));
        QPalette palette6;
        QBrush brush16(QColor(221, 221, 221, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        guestNameLabel->setPalette(palette6);
        guestNameLabel->setFont(font);
        datesStayingLabel = new QLabel(RoomReservation);
        datesStayingLabel->setObjectName(QStringLiteral("datesStayingLabel"));
        datesStayingLabel->setGeometry(QRect(30, 100, 111, 31));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        datesStayingLabel->setPalette(palette7);
        datesStayingLabel->setFont(font);
        guestNameDescription = new QLabel(RoomReservation);
        guestNameDescription->setObjectName(QStringLiteral("guestNameDescription"));
        guestNameDescription->setGeometry(QRect(30, 15, 201, 31));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        guestNameDescription->setPalette(palette8);
        QFont font3;
        font3.setFamily(QStringLiteral("Roboto Condensed"));
        font3.setPointSize(10);
        guestNameDescription->setFont(font3);
        datesDescription = new QLabel(RoomReservation);
        datesDescription->setObjectName(QStringLiteral("datesDescription"));
        datesDescription->setGeometry(QRect(30, 120, 321, 41));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        datesDescription->setPalette(palette9);
        datesDescription->setFont(font3);
        adultGuestsSpinBox = new QSpinBox(RoomReservation);
        adultGuestsSpinBox->setObjectName(QStringLiteral("adultGuestsSpinBox"));
        adultGuestsSpinBox->setGeometry(QRect(30, 270, 91, 31));
        adultGuestsSpinBox->setFont(font1);
        adultGuestsSpinBox->setMinimum(1);
        childrenGuestsSpinBox = new QSpinBox(RoomReservation);
        childrenGuestsSpinBox->setObjectName(QStringLiteral("childrenGuestsSpinBox"));
        childrenGuestsSpinBox->setGeometry(QRect(220, 270, 91, 31));
        childrenGuestsSpinBox->setFont(font1);
        adultsAndChildrenLabel = new QLabel(RoomReservation);
        adultsAndChildrenLabel->setObjectName(QStringLiteral("adultsAndChildrenLabel"));
        adultsAndChildrenLabel->setGeometry(QRect(20, 240, 331, 31));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        adultsAndChildrenLabel->setPalette(palette10);
        QFont font4;
        font4.setFamily(QStringLiteral("Roboto Condensed"));
        font4.setPointSize(9);
        adultsAndChildrenLabel->setFont(font4);
        nextPageButton = new QPushButton(RoomReservation);
        nextPageButton->setObjectName(QStringLiteral("nextPageButton"));
        nextPageButton->setGeometry(QRect(270, 430, 51, 22));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        nextPageButton->setPalette(palette11);
        nextPageButton->setFont(font1);
        roomTypeComboBox = new QComboBox(RoomReservation);
        roomTypeComboBox->setObjectName(QStringLiteral("roomTypeComboBox"));
        roomTypeComboBox->setGeometry(QRect(30, 50, 281, 31));
        roomTypeComboBox->setFont(font1);
        numNightsSpinBox = new QSpinBox(RoomReservation);
        numNightsSpinBox->setObjectName(QStringLiteral("numNightsSpinBox"));
        numNightsSpinBox->setGeometry(QRect(220, 170, 91, 31));
        numNightsSpinBox->setFont(font1);
        numNightsSpinBox->setStyleSheet(QStringLiteral("background-color: rgb(3, 79, 132);"));
        numNightsSpinBox->setMinimum(1);
        numNightsSpinBox->setMaximum(7);
        startingDateLabel = new QLabel(RoomReservation);
        startingDateLabel->setObjectName(QStringLiteral("startingDateLabel"));
        startingDateLabel->setGeometry(QRect(30, 150, 91, 16));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        startingDateLabel->setPalette(palette12);
        startingDateLabel->setFont(font4);
        numNightsLabel = new QLabel(RoomReservation);
        numNightsLabel->setObjectName(QStringLiteral("numNightsLabel"));
        numNightsLabel->setGeometry(QRect(220, 150, 91, 16));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        numNightsLabel->setPalette(palette13);
        numNightsLabel->setFont(font4);
        calendarWidget = new QCalendarWidget(RoomReservation);
        calendarWidget->setObjectName(QStringLiteral("calendarWidget"));
        calendarWidget->setGeometry(QRect(30, 200, 261, 161));
        calendarWidget->setFont(font3);
        calendarWidget->setStyleSheet(QStringLiteral("background-color: rgb(247, 120, 107);"));
        errorLabel = new QLabel(RoomReservation);
        errorLabel->setObjectName(QStringLiteral("errorLabel"));
        errorLabel->setGeometry(QRect(170, 390, 171, 41));
        errorLabel->setFont(font4);
        estimatedCostLabel = new QLabel(RoomReservation);
        estimatedCostLabel->setObjectName(QStringLiteral("estimatedCostLabel"));
        estimatedCostLabel->setGeometry(QRect(30, 400, 131, 21));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette14.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        estimatedCostLabel->setPalette(palette14);
        estimatedCostLabel->setFont(font);
        estimatedCostTargetLabel = new QLabel(RoomReservation);
        estimatedCostTargetLabel->setObjectName(QStringLiteral("estimatedCostTargetLabel"));
        estimatedCostTargetLabel->setGeometry(QRect(30, 420, 141, 41));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette15.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        estimatedCostTargetLabel->setPalette(palette15);
        QFont font5;
        font5.setFamily(QStringLiteral("Sans Serif"));
        font5.setPointSize(11);
        estimatedCostTargetLabel->setFont(font5);
        stackedWidget->addWidget(RoomReservation);
        parkingNeededLabel->raise();
        dateEdit->raise();
        numberOfGuestsLabel->raise();
        yesButton->raise();
        noButton->raise();
        guestNameDescription->raise();
        calendarPushButton->raise();
        datesDescription->raise();
        adultGuestsSpinBox->raise();
        childrenGuestsSpinBox->raise();
        adultsAndChildrenLabel->raise();
        nextPageButton->raise();
        roomTypeComboBox->raise();
        numNightsSpinBox->raise();
        startingDateLabel->raise();
        numNightsLabel->raise();
        errorLabel->raise();
        estimatedCostLabel->raise();
        estimatedCostTargetLabel->raise();
        guestNameLabel->raise();
        datesStayingLabel->raise();
        calendarWidget->raise();
        Payment = new QWidget();
        Payment->setObjectName(QStringLiteral("Payment"));
        nameOnCardTextEdit = new QPlainTextEdit(Payment);
        nameOnCardTextEdit->setObjectName(QStringLiteral("nameOnCardTextEdit"));
        nameOnCardTextEdit->setGeometry(QRect(30, 230, 281, 31));
        QPalette palette16;
        QBrush brush17(QColor(146, 168, 209, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette16.setBrush(QPalette::Active, QPalette::Button, brush17);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush17);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush17);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush17);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush17);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush17);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush17);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush17);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush17);
        nameOnCardTextEdit->setPalette(palette16);
        nameOnCardTextEdit->setStyleSheet(QStringLiteral("background-color: rgb(146, 168, 209);"));
        nameOnCardLabel = new QLabel(Payment);
        nameOnCardLabel->setObjectName(QStringLiteral("nameOnCardLabel"));
        nameOnCardLabel->setGeometry(QRect(30, 200, 151, 31));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette17.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        nameOnCardLabel->setPalette(palette17);
        QFont font6;
        font6.setFamily(QStringLiteral("Roboto"));
        font6.setPointSize(11);
        nameOnCardLabel->setFont(font6);
        cardNumberLabel = new QLabel(Payment);
        cardNumberLabel->setObjectName(QStringLiteral("cardNumberLabel"));
        cardNumberLabel->setGeometry(QRect(30, 330, 191, 51));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette18.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        cardNumberLabel->setPalette(palette18);
        cardNumberLabel->setFont(font6);
        cardTypeComboBox = new QComboBox(Payment);
        cardTypeComboBox->setObjectName(QStringLiteral("cardTypeComboBox"));
        cardTypeComboBox->setGeometry(QRect(30, 300, 281, 31));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette19.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette19.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette19.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        cardTypeComboBox->setPalette(palette19);
        cardTypeComboBox->setFont(font6);
        cardTypeLabel = new QLabel(Payment);
        cardTypeLabel->setObjectName(QStringLiteral("cardTypeLabel"));
        cardTypeLabel->setGeometry(QRect(30, 270, 151, 31));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette20.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette20.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette20.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette20.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette20.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette20.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette20.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        cardTypeLabel->setPalette(palette20);
        cardTypeLabel->setFont(font6);
        nextPageButton_2 = new QPushButton(Payment);
        nextPageButton_2->setObjectName(QStringLiteral("nextPageButton_2"));
        nextPageButton_2->setGeometry(QRect(270, 430, 51, 22));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette21.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette21.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette21.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette21.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette21.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette21.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette21.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette21.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette21.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette21.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette21.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        nextPageButton_2->setPalette(palette21);
        nextPageButton_2->setFont(font1);
        prevPageButton_2 = new QPushButton(Payment);
        prevPageButton_2->setObjectName(QStringLiteral("prevPageButton_2"));
        prevPageButton_2->setGeometry(QRect(220, 430, 51, 22));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette22.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette22.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette22.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette22.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette22.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette22.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette22.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        prevPageButton_2->setPalette(palette22);
        prevPageButton_2->setFont(font1);
        cardNumberInputBox = new QLineEdit(Payment);
        cardNumberInputBox->setObjectName(QStringLiteral("cardNumberInputBox"));
        cardNumberInputBox->setGeometry(QRect(30, 380, 131, 31));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::Button, brush17);
        palette23.setBrush(QPalette::Active, QPalette::Base, brush17);
        palette23.setBrush(QPalette::Active, QPalette::Window, brush17);
        palette23.setBrush(QPalette::Inactive, QPalette::Button, brush17);
        palette23.setBrush(QPalette::Inactive, QPalette::Base, brush17);
        palette23.setBrush(QPalette::Inactive, QPalette::Window, brush17);
        palette23.setBrush(QPalette::Disabled, QPalette::Button, brush17);
        palette23.setBrush(QPalette::Disabled, QPalette::Base, brush17);
        palette23.setBrush(QPalette::Disabled, QPalette::Window, brush17);
        cardNumberInputBox->setPalette(palette23);
        cardNumberInputBox->setFont(font1);
        cardNumberInputBox->setStyleSheet(QStringLiteral("background-color: rgb(146, 168, 209);"));
        expirationMonthSpinBox = new QSpinBox(Payment);
        expirationMonthSpinBox->setObjectName(QStringLiteral("expirationMonthSpinBox"));
        expirationMonthSpinBox->setGeometry(QRect(200, 380, 41, 31));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::Button, brush17);
        palette24.setBrush(QPalette::Active, QPalette::Base, brush17);
        palette24.setBrush(QPalette::Active, QPalette::Window, brush17);
        palette24.setBrush(QPalette::Inactive, QPalette::Button, brush17);
        palette24.setBrush(QPalette::Inactive, QPalette::Base, brush17);
        palette24.setBrush(QPalette::Inactive, QPalette::Window, brush17);
        palette24.setBrush(QPalette::Disabled, QPalette::Button, brush17);
        palette24.setBrush(QPalette::Disabled, QPalette::Base, brush17);
        palette24.setBrush(QPalette::Disabled, QPalette::Window, brush17);
        expirationMonthSpinBox->setPalette(palette24);
        expirationMonthSpinBox->setFont(font6);
        expirationMonthSpinBox->setStyleSheet(QStringLiteral("background-color: rgb(146, 168, 209);"));
        expirationMonthSpinBox->setMinimum(1);
        expirationMonthSpinBox->setMaximum(12);
        expirationYearSpinBox = new QSpinBox(Payment);
        expirationYearSpinBox->setObjectName(QStringLiteral("expirationYearSpinBox"));
        expirationYearSpinBox->setGeometry(QRect(261, 380, 61, 31));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::Button, brush17);
        palette25.setBrush(QPalette::Active, QPalette::Base, brush17);
        palette25.setBrush(QPalette::Active, QPalette::Window, brush17);
        palette25.setBrush(QPalette::Inactive, QPalette::Button, brush17);
        palette25.setBrush(QPalette::Inactive, QPalette::Base, brush17);
        palette25.setBrush(QPalette::Inactive, QPalette::Window, brush17);
        palette25.setBrush(QPalette::Disabled, QPalette::Button, brush17);
        palette25.setBrush(QPalette::Disabled, QPalette::Base, brush17);
        palette25.setBrush(QPalette::Disabled, QPalette::Window, brush17);
        expirationYearSpinBox->setPalette(palette25);
        expirationYearSpinBox->setFont(font6);
        expirationYearSpinBox->setStyleSheet(QStringLiteral("background-color: rgb(146, 168, 209);"));
        expirationYearSpinBox->setMinimum(2020);
        expirationYearSpinBox->setMaximum(2050);
        expirationMonthLabel = new QLabel(Payment);
        expirationMonthLabel->setObjectName(QStringLiteral("expirationMonthLabel"));
        expirationMonthLabel->setGeometry(QRect(200, 360, 51, 20));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette26.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette26.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette26.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette26.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette26.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette26.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette26.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette26.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette26.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette26.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette26.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        expirationMonthLabel->setPalette(palette26);
        expirationMonthLabel->setFont(font4);
        expirationYearLabel = new QLabel(Payment);
        expirationYearLabel->setObjectName(QStringLiteral("expirationYearLabel"));
        expirationYearLabel->setGeometry(QRect(260, 360, 51, 21));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette27.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette27.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette27.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette27.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette27.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette27.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette27.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette27.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        expirationYearLabel->setPalette(palette27);
        expirationYearLabel->setFont(font4);
        expirationLabel = new QLabel(Payment);
        expirationLabel->setObjectName(QStringLiteral("expirationLabel"));
        expirationLabel->setGeometry(QRect(216, 330, 61, 41));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette28.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette28.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette28.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette28.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette28.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette28.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette28.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette28.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        expirationLabel->setPalette(palette28);
        expirationLabel->setFont(font1);
        chargesLabel = new QLabel(Payment);
        chargesLabel->setObjectName(QStringLiteral("chargesLabel"));
        chargesLabel->setGeometry(QRect(30, 0, 81, 21));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette29.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette29.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette29.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette29.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette29.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette29.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette29.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette29.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette29.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette29.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette29.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        chargesLabel->setPalette(palette29);
        chargesLabel->setFont(font);
        roomCostLabel = new QLabel(Payment);
        roomCostLabel->setObjectName(QStringLiteral("roomCostLabel"));
        roomCostLabel->setGeometry(QRect(30, 30, 57, 21));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette30.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette30.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette30.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette30.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette30.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette30.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette30.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette30.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette30.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette30.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette30.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        roomCostLabel->setPalette(palette30);
        roomCostLabel->setFont(font6);
        parkingCostLabel = new QLabel(Payment);
        parkingCostLabel->setObjectName(QStringLiteral("parkingCostLabel"));
        parkingCostLabel->setGeometry(QRect(180, 30, 71, 21));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette31.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette31.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette31.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette31.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette31.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette31.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette31.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette31.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette31.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette31.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette31.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        parkingCostLabel->setPalette(palette31);
        parkingCostLabel->setFont(font6);
        resortFeesCostLabel = new QLabel(Payment);
        resortFeesCostLabel->setObjectName(QStringLiteral("resortFeesCostLabel"));
        resortFeesCostLabel->setGeometry(QRect(180, 80, 101, 21));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette32.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette32.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette32.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette32.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette32.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette32.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette32.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette32.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette32.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette32.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette32.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        resortFeesCostLabel->setPalette(palette32);
        resortFeesCostLabel->setFont(font6);
        taxCostLabel = new QLabel(Payment);
        taxCostLabel->setObjectName(QStringLiteral("taxCostLabel"));
        taxCostLabel->setGeometry(QRect(30, 80, 57, 21));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette33.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette33.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette33.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        taxCostLabel->setPalette(palette33);
        taxCostLabel->setFont(font6);
        totalCostLabel = new QLabel(Payment);
        totalCostLabel->setObjectName(QStringLiteral("totalCostLabel"));
        totalCostLabel->setGeometry(QRect(30, 120, 81, 16));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette34.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette34.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette34.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette34.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette34.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette34.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette34.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette34.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette34.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette34.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette34.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        totalCostLabel->setPalette(palette34);
        totalCostLabel->setFont(font);
        totalCostDollarsLabel = new QLabel(Payment);
        totalCostDollarsLabel->setObjectName(QStringLiteral("totalCostDollarsLabel"));
        totalCostDollarsLabel->setGeometry(QRect(30, 143, 61, 21));
        QPalette palette35;
        palette35.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette35.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette35.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette35.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette35.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette35.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette35.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette35.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette35.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        totalCostDollarsLabel->setPalette(palette35);
        QFont font7;
        font7.setPointSize(11);
        totalCostDollarsLabel->setFont(font7);
        parkingCostDollarsLabel = new QLabel(Payment);
        parkingCostDollarsLabel->setObjectName(QStringLiteral("parkingCostDollarsLabel"));
        parkingCostDollarsLabel->setGeometry(QRect(280, 30, 57, 21));
        QPalette palette36;
        palette36.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette36.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette36.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette36.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette36.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette36.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette36.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette36.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette36.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        parkingCostDollarsLabel->setPalette(palette36);
        QFont font8;
        font8.setPointSize(10);
        parkingCostDollarsLabel->setFont(font8);
        roomDollarsLabel = new QLabel(Payment);
        roomDollarsLabel->setObjectName(QStringLiteral("roomDollarsLabel"));
        roomDollarsLabel->setGeometry(QRect(100, 30, 57, 21));
        QPalette palette37;
        palette37.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette37.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette37.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette37.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette37.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette37.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette37.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette37.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette37.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        roomDollarsLabel->setPalette(palette37);
        roomDollarsLabel->setFont(font8);
        taxDollarsLabel = new QLabel(Payment);
        taxDollarsLabel->setObjectName(QStringLiteral("taxDollarsLabel"));
        taxDollarsLabel->setGeometry(QRect(100, 80, 57, 21));
        QPalette palette38;
        palette38.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette38.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette38.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette38.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette38.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette38.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette38.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette38.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette38.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette38.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette38.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette38.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        taxDollarsLabel->setPalette(palette38);
        taxDollarsLabel->setFont(font8);
        resortFeesDollarsLabel = new QLabel(Payment);
        resortFeesDollarsLabel->setObjectName(QStringLiteral("resortFeesDollarsLabel"));
        resortFeesDollarsLabel->setGeometry(QRect(280, 80, 57, 21));
        QPalette palette39;
        palette39.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette39.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette39.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette39.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette39.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette39.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette39.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette39.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette39.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette39.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette39.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette39.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        resortFeesDollarsLabel->setPalette(palette39);
        resortFeesDollarsLabel->setFont(font8);
        paymentInformationLabel = new QLabel(Payment);
        paymentInformationLabel->setObjectName(QStringLiteral("paymentInformationLabel"));
        paymentInformationLabel->setGeometry(QRect(30, 170, 191, 41));
        QPalette palette40;
        palette40.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette40.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette40.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette40.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette40.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette40.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette40.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette40.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette40.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette40.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette40.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette40.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        paymentInformationLabel->setPalette(palette40);
        paymentInformationLabel->setFont(font);
        payButton = new QPushButton(Payment);
        payButton->setObjectName(QStringLiteral("payButton"));
        payButton->setGeometry(QRect(30, 421, 131, 31));
        QPalette palette41;
        QBrush brush18(QColor(247, 120, 107, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette41.setBrush(QPalette::Active, QPalette::Button, brush18);
        palette41.setBrush(QPalette::Active, QPalette::Base, brush18);
        palette41.setBrush(QPalette::Active, QPalette::Window, brush18);
        palette41.setBrush(QPalette::Inactive, QPalette::Button, brush18);
        palette41.setBrush(QPalette::Inactive, QPalette::Base, brush18);
        palette41.setBrush(QPalette::Inactive, QPalette::Window, brush18);
        palette41.setBrush(QPalette::Disabled, QPalette::Button, brush18);
        palette41.setBrush(QPalette::Disabled, QPalette::Base, brush18);
        palette41.setBrush(QPalette::Disabled, QPalette::Window, brush18);
        payButton->setPalette(palette41);
        payButton->setStyleSheet(QStringLiteral("background-color: rgb(247, 120, 107);"));
        stackedWidget->addWidget(Payment);
        nameOnCardTextEdit->raise();
        nameOnCardLabel->raise();
        cardNumberLabel->raise();
        cardTypeComboBox->raise();
        cardTypeLabel->raise();
        nextPageButton_2->raise();
        prevPageButton_2->raise();
        cardNumberInputBox->raise();
        expirationMonthSpinBox->raise();
        expirationYearSpinBox->raise();
        expirationLabel->raise();
        chargesLabel->raise();
        roomCostLabel->raise();
        parkingCostLabel->raise();
        resortFeesCostLabel->raise();
        taxCostLabel->raise();
        totalCostLabel->raise();
        totalCostDollarsLabel->raise();
        parkingCostDollarsLabel->raise();
        roomDollarsLabel->raise();
        taxDollarsLabel->raise();
        resortFeesDollarsLabel->raise();
        paymentInformationLabel->raise();
        payButton->raise();
        expirationMonthLabel->raise();
        expirationYearLabel->raise();
        ConfirmationPage = new QWidget();
        ConfirmationPage->setObjectName(QStringLiteral("ConfirmationPage"));
        reservationDetailsLabel = new QLabel(ConfirmationPage);
        reservationDetailsLabel->setObjectName(QStringLiteral("reservationDetailsLabel"));
        reservationDetailsLabel->setGeometry(QRect(110, 0, 151, 21));
        QPalette palette42;
        palette42.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette42.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette42.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette42.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette42.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette42.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette42.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette42.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette42.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette42.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette42.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette42.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette42.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette42.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette42.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        reservationDetailsLabel->setPalette(palette42);
        firstDayLabel = new QLabel(ConfirmationPage);
        firstDayLabel->setObjectName(QStringLiteral("firstDayLabel"));
        firstDayLabel->setGeometry(QRect(190, 80, 171, 20));
        QPalette palette43;
        palette43.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette43.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette43.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette43.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette43.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette43.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette43.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette43.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette43.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette43.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette43.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette43.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette43.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette43.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette43.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        firstDayLabel->setPalette(palette43);
        firstDayLabel->setFont(font7);
        howManyNightsLabel = new QLabel(ConfirmationPage);
        howManyNightsLabel->setObjectName(QStringLiteral("howManyNightsLabel"));
        howManyNightsLabel->setGeometry(QRect(10, 70, 171, 41));
        QPalette palette44;
        palette44.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette44.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette44.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette44.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette44.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette44.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette44.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette44.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette44.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette44.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette44.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette44.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette44.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette44.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette44.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        howManyNightsLabel->setPalette(palette44);
        howManyNightsLabel->setFont(font7);
        roomTypeLabel = new QLabel(ConfirmationPage);
        roomTypeLabel->setObjectName(QStringLiteral("roomTypeLabel"));
        roomTypeLabel->setGeometry(QRect(10, 30, 181, 21));
        QPalette palette45;
        palette45.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette45.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette45.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette45.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette45.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette45.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette45.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette45.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette45.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        roomTypeLabel->setPalette(palette45);
        roomTypeLabel->setFont(font7);
        parkingLabel = new QLabel(ConfirmationPage);
        parkingLabel->setObjectName(QStringLiteral("parkingLabel"));
        parkingLabel->setGeometry(QRect(190, 30, 141, 21));
        QPalette palette46;
        palette46.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette46.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette46.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette46.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette46.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette46.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette46.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette46.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette46.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette46.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette46.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette46.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette46.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette46.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette46.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        parkingLabel->setPalette(palette46);
        parkingLabel->setFont(font7);
        adultsLabel = new QLabel(ConfirmationPage);
        adultsLabel->setObjectName(QStringLiteral("adultsLabel"));
        adultsLabel->setGeometry(QRect(10, 130, 171, 21));
        QPalette palette47;
        palette47.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette47.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette47.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette47.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette47.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette47.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette47.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette47.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette47.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette47.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette47.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette47.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette47.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette47.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette47.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        adultsLabel->setPalette(palette47);
        adultsLabel->setFont(font7);
        childrenLabel = new QLabel(ConfirmationPage);
        childrenLabel->setObjectName(QStringLiteral("childrenLabel"));
        childrenLabel->setGeometry(QRect(190, 110, 171, 61));
        QPalette palette48;
        palette48.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette48.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette48.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette48.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette48.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette48.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette48.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette48.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette48.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette48.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette48.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette48.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette48.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette48.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette48.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        childrenLabel->setPalette(palette48);
        childrenLabel->setFont(font7);
        paymentInformationLabel_2 = new QLabel(ConfirmationPage);
        paymentInformationLabel_2->setObjectName(QStringLiteral("paymentInformationLabel_2"));
        paymentInformationLabel_2->setGeometry(QRect(90, 180, 181, 21));
        QPalette palette49;
        palette49.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette49.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette49.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette49.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette49.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette49.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette49.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette49.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette49.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette49.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette49.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette49.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette49.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette49.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette49.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        paymentInformationLabel_2->setPalette(palette49);
        QFont font9;
        font9.setPointSize(12);
        paymentInformationLabel_2->setFont(font9);
        totalAmountLabel = new QLabel(ConfirmationPage);
        totalAmountLabel->setObjectName(QStringLiteral("totalAmountLabel"));
        totalAmountLabel->setGeometry(QRect(10, 210, 351, 21));
        QPalette palette50;
        palette50.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette50.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette50.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette50.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette50.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette50.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette50.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette50.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette50.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette50.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette50.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette50.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette50.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette50.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette50.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        totalAmountLabel->setPalette(palette50);
        totalAmountLabel->setFont(font7);
        paidWithCardLabel = new QLabel(ConfirmationPage);
        paidWithCardLabel->setObjectName(QStringLiteral("paidWithCardLabel"));
        paidWithCardLabel->setGeometry(QRect(10, 260, 351, 21));
        QPalette palette51;
        palette51.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette51.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette51.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette51.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette51.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette51.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette51.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette51.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette51.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette51.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette51.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette51.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette51.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette51.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette51.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        paidWithCardLabel->setPalette(palette51);
        paidWithCardLabel->setFont(font7);
        closeButton = new QPushButton(ConfirmationPage);
        closeButton->setObjectName(QStringLiteral("closeButton"));
        closeButton->setGeometry(QRect(280, 420, 80, 22));
        QPalette palette52;
        palette52.setBrush(QPalette::Active, QPalette::Button, brush18);
        palette52.setBrush(QPalette::Active, QPalette::Base, brush18);
        palette52.setBrush(QPalette::Active, QPalette::Window, brush18);
        palette52.setBrush(QPalette::Inactive, QPalette::Button, brush18);
        palette52.setBrush(QPalette::Inactive, QPalette::Base, brush18);
        palette52.setBrush(QPalette::Inactive, QPalette::Window, brush18);
        palette52.setBrush(QPalette::Disabled, QPalette::Button, brush18);
        palette52.setBrush(QPalette::Disabled, QPalette::Base, brush18);
        palette52.setBrush(QPalette::Disabled, QPalette::Window, brush18);
        closeButton->setPalette(palette52);
        closeButton->setStyleSheet(QStringLiteral("background-color: rgb(247, 120, 107);"));
        closingLabel = new QLabel(ConfirmationPage);
        closingLabel->setObjectName(QStringLiteral("closingLabel"));
        closingLabel->setGeometry(QRect(30, 320, 311, 51));
        QPalette palette53;
        palette53.setBrush(QPalette::Active, QPalette::WindowText, brush16);
        palette53.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette53.setBrush(QPalette::Active, QPalette::ButtonText, brush16);
        palette53.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette53.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::WindowText, brush16);
        palette53.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::ButtonText, brush16);
        palette53.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette53.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette53.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        closingLabel->setPalette(palette53);
        QFont font10;
        font10.setPointSize(14);
        closingLabel->setFont(font10);
        stackedWidget->addWidget(ConfirmationPage);
        ReservationWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(ReservationWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 367, 19));
        ReservationWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(ReservationWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        ReservationWindow->setStatusBar(statusbar);

        retranslateUi(ReservationWindow);

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(ReservationWindow);
    } // setupUi

    void retranslateUi(QMainWindow *ReservationWindow)
    {
        ReservationWindow->setWindowTitle(QApplication::translate("ReservationWindow", "ReservationWindow", Q_NULLPTR));
        parkingNeededLabel->setText(QApplication::translate("ReservationWindow", "Parking Needed ($12.50/night) :", Q_NULLPTR));
        calendarPushButton->setText(QString());
        numberOfGuestsLabel->setText(QApplication::translate("ReservationWindow", "Guests Staying:", Q_NULLPTR));
        yesButton->setText(QApplication::translate("ReservationWindow", "Yes", Q_NULLPTR));
        noButton->setText(QApplication::translate("ReservationWindow", "No", Q_NULLPTR));
        guestNameLabel->setText(QApplication::translate("ReservationWindow", "Room Type", Q_NULLPTR));
        datesStayingLabel->setText(QApplication::translate("ReservationWindow", "Dates Staying:", Q_NULLPTR));
        guestNameDescription->setText(QApplication::translate("ReservationWindow", "Please select a room type:", Q_NULLPTR));
        datesDescription->setText(QApplication::translate("ReservationWindow", "Please enter the starting date for the reservation (max 7 days):", Q_NULLPTR));
        adultsAndChildrenLabel->setText(QApplication::translate("ReservationWindow", "      Adults:                                                         Children (17 and under):", Q_NULLPTR));
        nextPageButton->setText(QApplication::translate("ReservationWindow", "Next ->", Q_NULLPTR));
        roomTypeComboBox->clear();
        roomTypeComboBox->insertItems(0, QStringList()
         << QApplication::translate("ReservationWindow", "---", Q_NULLPTR)
         << QApplication::translate("ReservationWindow", "Standard 2-queen room ($284/night)", Q_NULLPTR)
         << QApplication::translate("ReservationWindow", "Atrium 2-queen room ($325/night)", Q_NULLPTR)
         << QApplication::translate("ReservationWindow", "Standard 1-king room ($290/night)", Q_NULLPTR)
         << QApplication::translate("ReservationWindow", "Atrium 1-king room ($350/night)", Q_NULLPTR)
        );
        startingDateLabel->setText(QApplication::translate("ReservationWindow", "Starting Date:", Q_NULLPTR));
        numNightsLabel->setText(QApplication::translate("ReservationWindow", "Number of Nights:", Q_NULLPTR));
        errorLabel->setText(QString());
        estimatedCostLabel->setText(QApplication::translate("ReservationWindow", "Estimated Cost:", Q_NULLPTR));
        estimatedCostTargetLabel->setText(QApplication::translate("ReservationWindow", "$0.00", Q_NULLPTR));
        nameOnCardTextEdit->setPlainText(QString());
        nameOnCardLabel->setText(QApplication::translate("ReservationWindow", "Name on Card", Q_NULLPTR));
        cardNumberLabel->setText(QApplication::translate("ReservationWindow", "Debit/Credit card number", Q_NULLPTR));
        cardTypeComboBox->clear();
        cardTypeComboBox->insertItems(0, QStringList()
         << QApplication::translate("ReservationWindow", "American Express", Q_NULLPTR)
         << QApplication::translate("ReservationWindow", "Visa", Q_NULLPTR)
         << QApplication::translate("ReservationWindow", "Mastercard", Q_NULLPTR)
         << QApplication::translate("ReservationWindow", "Discover", Q_NULLPTR)
        );
        cardTypeLabel->setText(QApplication::translate("ReservationWindow", "Card Type", Q_NULLPTR));
        nextPageButton_2->setText(QApplication::translate("ReservationWindow", "Next ->", Q_NULLPTR));
        prevPageButton_2->setText(QApplication::translate("ReservationWindow", "<- Prev", Q_NULLPTR));
        cardNumberInputBox->setInputMask(QApplication::translate("ReservationWindow", "0000 000000 00000;_", Q_NULLPTR));
        expirationMonthLabel->setText(QApplication::translate("ReservationWindow", "Month", Q_NULLPTR));
        expirationYearLabel->setText(QApplication::translate("ReservationWindow", "Year", Q_NULLPTR));
        expirationLabel->setText(QApplication::translate("ReservationWindow", "Expiration", Q_NULLPTR));
        chargesLabel->setText(QApplication::translate("ReservationWindow", "Charges:", Q_NULLPTR));
        roomCostLabel->setText(QApplication::translate("ReservationWindow", "Room:", Q_NULLPTR));
        parkingCostLabel->setText(QApplication::translate("ReservationWindow", "Parking:", Q_NULLPTR));
        resortFeesCostLabel->setText(QApplication::translate("ReservationWindow", "Resort Fees:", Q_NULLPTR));
        taxCostLabel->setText(QApplication::translate("ReservationWindow", "Tax:", Q_NULLPTR));
        totalCostLabel->setText(QApplication::translate("ReservationWindow", "Total Cost:", Q_NULLPTR));
        totalCostDollarsLabel->setText(QApplication::translate("ReservationWindow", "$0.00", Q_NULLPTR));
        parkingCostDollarsLabel->setText(QApplication::translate("ReservationWindow", "$0.00", Q_NULLPTR));
        roomDollarsLabel->setText(QApplication::translate("ReservationWindow", "$0.00", Q_NULLPTR));
        taxDollarsLabel->setText(QApplication::translate("ReservationWindow", "$0.00", Q_NULLPTR));
        resortFeesDollarsLabel->setText(QApplication::translate("ReservationWindow", "$0.00", Q_NULLPTR));
        paymentInformationLabel->setText(QApplication::translate("ReservationWindow", "Payment Information:", Q_NULLPTR));
        payButton->setText(QApplication::translate("ReservationWindow", "Pay Now!", Q_NULLPTR));
        reservationDetailsLabel->setText(QApplication::translate("ReservationWindow", "Reservation Details:", Q_NULLPTR));
        firstDayLabel->setText(QApplication::translate("ReservationWindow", "First day:", Q_NULLPTR));
        howManyNightsLabel->setText(QApplication::translate("ReservationWindow", "How many nights:", Q_NULLPTR));
        roomTypeLabel->setText(QApplication::translate("ReservationWindow", "Room Type:", Q_NULLPTR));
        parkingLabel->setText(QApplication::translate("ReservationWindow", "Parking:", Q_NULLPTR));
        adultsLabel->setText(QApplication::translate("ReservationWindow", "Adults:", Q_NULLPTR));
        childrenLabel->setText(QApplication::translate("ReservationWindow", "Children:", Q_NULLPTR));
        paymentInformationLabel_2->setText(QApplication::translate("ReservationWindow", "Payment Information:", Q_NULLPTR));
        totalAmountLabel->setText(QApplication::translate("ReservationWindow", "Total Amount:", Q_NULLPTR));
        paidWithCardLabel->setText(QApplication::translate("ReservationWindow", "Paid with credit card ending in ", Q_NULLPTR));
        closeButton->setText(QApplication::translate("ReservationWindow", "Close", Q_NULLPTR));
        closingLabel->setText(QApplication::translate("ReservationWindow", "Thanks for choosing Exspeedia!", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class ReservationWindow: public Ui_ReservationWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_RESERVATIONWINDOW_H
